### ISSUE TITLE
Document Attributes in the Model

### ISSUE THREAD

**Issue by dmlb2000** [EMSL-MSC/pacifica-metadata#11]
We should document the attributes in each of the model bits to describe what they represent for that part of the model.

```
    Attributes:
        +-------------------+-------------------------------------+
        | Name              | Description                         |
        +===================+=====================================+
        | citation          | Link to the Citation model          |
        +-------------------+-------------------------------------+
        | author            | Link to the Contributor model       |
        +-------------------+-------------------------------------+
        | author_precedence | Order of the Author in the Citation |
        +-------------------+-------------------------------------+
```

**Comment by dmlb2000** [comment]
As part of this I'll be determining if certain attributes don't need to be there. Extra tickets will be put in place to remove those attributes when/if they are found.

**Comment by dmlb2000** [comment]
@markborkum @kauberry any idea what the `institutions.association_cd` might represent in `metadata/orm/institutions.py`?

**Comment by markborkum** [comment]
@dmlb2000 In user proposal forms, for each participant, there is a field for "Institution Type" that maps to the`ASSOCIATION_DESC` column in the user proposal database. Perhaps "CD" is a typo for "DESC"?
