### ISSUE TITLE
Update Metadata Model Dia

### ISSUE THREAD

**Issue by dmlb2000** [EMSL-MSC/pacifica-metadata#17]
Since the new metadata additions we'd like to keep the Metadata Model Dia files in sync...

**Comment by markborkum** [comment]
@dmlb2000 In the auto-generated Markdown, some models have columns for both an association and its foreign key (e.g., `Citations` has `journal` and `journal_id` attributes.) Should both columns be included in the Dia file?

**Comment by dmlb2000** [comment]
I noticed the PeeWee changes to the model, I'm wondering if this was a minor version bump in PeeWee or something else. I'm still investigating it, so ignore the duplicate `_id` fields for now.
