### ISSUE TITLE
IETF Language Tags

### ISSUE THREAD

**Issue by markborkum** [EMSL-MSC/pacifica-metadata#3]
Language-dependent textual entities, such as titles and abstracts, should have [IETF language tags](https://en.wikipedia.org/wiki/IETF_language_tag).

For example:
- Citations.abstract_text
- Citations.article_title
- Groups.group_name
- Institutions.institution_name
- Instruments.instrument_name
- Journals.journal_name
- Keywords.keyword
- Proposals.abstract
- Proposals.title

Whether each entity should assert a separate language tag, or if the entire record should assert a single language tag, is a matter of discussion.

**Comment by dmlb2000** [comment]
We'll also have to make sure all these attributes get unicode conversions instead of string...

**Comment by markborkum** [comment]
If you're using PostgreSQL under the hood, this [documentation](https://www.postgresql.org/docs/current/static/multibyte.html) may be of use.

**Comment by dmlb2000** [comment]
@markborkum would it be sufficient to add a single language tag per object and assume all attributes of the object have that language?

**Comment by markborkum** [comment]
Ostensibly, yes. One language tag per object would be sufficient for current purposes.

In the future, however, we may want to provide translations for specific attributes. In which case, we would need to implement a separate "LangStrings" table.

**Comment by dmlb2000** [comment]
I think the pull request is complete...
