### ISSUE TITLE
'deleted' field not defaulting to NULL

### ISSUE THREAD

**Issue by kauberry** [EMSL-MSC/pacifica-metadata#44]
When inserting values through the REST interface, something is causing the 'deleted' value to be populated with a value that looks suspiciously like an epoch of 0 (zero, that is), instead of a NULL.

    id      created              updated               deleted              first_name   last_name  network_id   encoding
    43751	2016-10-11 23:11:51  2016-10-11 23:11:51   1970-01-01 00:00:00	Ken          Auberry	d3k857       UTF8

I looked around for something obvious, but I'm missing it. It's not the database proper, but rather in the actual query that is going across the wire.

    INSERT INTO "users" (
        "id", "created", "updated", "deleted", "first_name",
        "middle_initial", "last_name", "network_id",
        "email_address", "encoding") 
    VALUES (
        43751, '2016-10-11T23:11:51'::timestamp,
        '2016-10-11T23:11:51'::timestamp, '1970-01-01T00:00:00'::timestamp,
        'Ken', '', 'Auberry', 'd3k857', '', 'UTF8') RETURNING "id"

Thoughts??

**Comment by dmlb2000** [comment]
It seems like we need to change line 73 and line 94 that need to be changed to set deleted to None instead of datetime of 0 in the metadata.rest.orm. We should also add some testing to validate this behaviour... add query for stuff deleted and query for stuff not deleted and validate both sides...
