### ISSUE TITLE
MIME Types

### ISSUE THREAD

**Issue by markborkum** [EMSL-MSC/pacifica-metadata#5]
"Files" should assert a MIME type.

**Comment by dmlb2000** [comment]
@markborkum Did you use a tool to generate the dia file or was that manual?

**Comment by markborkum** [comment]
@dmlb2000 Manual. If final layout is not an issue, we could write a tool that generates GraphViz "dot" files.

**Comment by dmlb2000** [comment]
This is merged must have done the comment wrong...
